<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>FilterPriceList</name>
   <tag></tag>
   <elementGuidId>3b3e85c7-30e7-4127-81d4-139148130e24</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class='productListing']//div[@class='row']//div[@class='price-section-listview']//span[contains(@class,'price')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class='productListing']//div[@class='row']//div[@class='price-section-listview']//span[contains(@class,'price')]</value>
      <webElementGuid>21161690-745d-4586-8e02-279e21f80130</webElementGuid>
   </webElementProperties>
</WebElementEntity>
