<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Filter_SelectMaxPrice</name>
   <tag></tag>
   <elementGuidId>a98362ba-2b2e-468c-9625-c33860e09c2d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#priceDropMax</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//select[@id='priceDropMax']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@class='deleteFilter']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>cf5d80ae-a8ef-4d0c-87ec-e3c544a46435</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>86c594a7-45a9-437a-a26a-68ce6cbaebad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>priceDropMax</value>
      <webElementGuid>b25b9718-06a9-4fd9-baa0-197ca03f5f33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>priceDropMax</value>
      <webElementGuid>c3589111-b878-49dc-bb2a-daddfdc18b04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>5000150002500050000100000100000+</value>
      <webElementGuid>fc445773-8fa7-4e58-be9d-bd6c0e9669da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//select[@id='priceDropMax']</value>
      <webElementGuid>764b4de0-4c68-4069-8d75-19fd1356105c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='priceDropMax']</value>
      <webElementGuid>cc70ab3a-f364-4afe-b47b-6e6c4f4c4930</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-wrapper']/div/div[6]/div/div/div/div[2]/div/div/ul/li[2]/div[4]/div[2]/select</value>
      <webElementGuid>41e84b8f-3a75-48a8-bbde-f1a02cd63820</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Price'])[2]/following::select[2]</value>
      <webElementGuid>cd6b0c38-adfd-477c-9f50-f385d9145402</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Price'])[1]/following::select[2]</value>
      <webElementGuid>5352e664-97bc-473a-ab1a-81ac215eb406</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='By Category'])[2]/preceding::select[1]</value>
      <webElementGuid>b957a044-6418-457c-8670-81ef0af7686b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Accessories'])[1]/preceding::select[1]</value>
      <webElementGuid>9396d610-3c32-464e-b5f6-d2c9cea9c983</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/select</value>
      <webElementGuid>1e35db5b-f77f-4c49-868d-a9f1c8e0d4c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'priceDropMax' and @name = 'priceDropMax' and (text() = '5000150002500050000100000100000+' or . = '5000150002500050000100000100000+')]</value>
      <webElementGuid>ce04fec0-d70f-4995-b494-fab467f2627c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
