<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>FilterPrice_Range</name>
   <tag></tag>
   <elementGuidId>4db025db-cc05-45ee-a64c-293f2646cb80</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.deleteFilter</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='filters-top-selected_price']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>366d8c08-02a2-409a-a6f1-7db08f4e4f66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>deleteFilter</value>
      <webElementGuid>46f1f283-7073-47af-8e10-b09253428e45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>refinerel</name>
      <type>Main</type>
      <value>price</value>
      <webElementGuid>192de5bf-c27e-4d01-a2c8-47aeb541750e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>refineurl</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>8a84d9c0-5236-4b1d-9a01-5963fc6f369b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Remove price</value>
      <webElementGuid>ec4333ac-77d8-481d-b75f-14d680367ae1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>Javascript:void(0);</value>
      <webElementGuid>01c9a097-241d-4d87-b5ac-f2d5e415f036</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>price</value>
      <webElementGuid>5285f0e5-9f14-41c4-b376-076ed811fe37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>0 - 15,000</value>
      <webElementGuid>213fd7c3-b2e3-41f7-b2a5-c8ff93381c6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;filters-top-selected_price&quot;)/a[@class=&quot;deleteFilter&quot;]</value>
      <webElementGuid>26f66f2c-a641-433a-a471-71a19eb0707a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='filters-top-selected_price']/a</value>
      <webElementGuid>b2500a02-e699-4f02-a7ee-d83f80291570</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FILTERED BY'])[1]/following::a[1]</value>
      <webElementGuid>32c05214-f1c2-43e2-a592-0bf31ed10a32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BUY NOW'])[1]/preceding::a[3]</value>
      <webElementGuid>5fb851f8-6912-4c0c-a54d-18b4d6e06ee3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VIEW DETAILS'])[1]/preceding::a[4]</value>
      <webElementGuid>f764b1ea-906f-4d30-bbca-8268413a7364</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'Javascript:void(0);')])[44]</value>
      <webElementGuid>98901a5f-fac8-4b6b-bb53-4c2099a3daf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a</value>
      <webElementGuid>412a5d2d-577e-483d-8edf-96905c6cf799</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = 'Remove price' and @href = 'Javascript:void(0);' and (text() = '0 - 15,000' or . = '0 - 15,000')]</value>
      <webElementGuid>90f419c2-3ca3-4588-84a2-e9e8acf2c082</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
