<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_The Gold Chain GCH00690002 Ships Faster</name>
   <tag></tag>
   <elementGuidId>2f381499-5b61-4134-8283-fcb39a4a98b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='prodListingUl']/li[2]/div/div[2]/div/div/div/h2/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b2c172e7-3516-4298-97f9-48fe840ce4c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/the-gold-chain-gch00690002-ships-faster.html?bid=MTkyMg==</value>
      <webElementGuid>dd6e26ee-ac4d-49d4-a9de-7261ba6188e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>6acbab1b-638a-4811-8af4-b46f8bd70686</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>The Gold Chain GCH00690002 Ships Faster</value>
      <webElementGuid>70395c20-5ffc-451a-8695-16b67fa98bbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;prodListingUl&quot;)/li[@class=&quot;col-xs-6  col-lg-3 pdt-item-list&quot;]/div[@class=&quot;bx-contr&quot;]/div[@class=&quot;deatils pos-rel&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-12 title-section text-center ss&quot;]/div[@class=&quot;hidden-xs&quot;]/h2[@class=&quot;productTitle h5style font-medium rmv-padding text-overflow margin-bottom&quot;]/a[1]</value>
      <webElementGuid>e349aae5-6a21-4451-8378-f1e29e5a0691</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='prodListingUl']/li[2]/div/div[2]/div/div/div/h2/a</value>
      <webElementGuid>85157148-b7c4-4e73-93ce-98489356d195</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'The Gold Chain GCH00690002 Ships Faster')]</value>
      <webElementGuid>d8a7c258-eeec-41c3-8c5b-c8db3b5e9ffc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VIEW DETAILS'])[3]/following::a[2]</value>
      <webElementGuid>ecda117e-5a50-498f-bd92-c090a492fbd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BUY NOW'])[3]/following::a[3]</value>
      <webElementGuid>0d04ca22-f286-4ddc-833b-2cf0be302f8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='₹122,253'])[1]/preceding::a[1]</value>
      <webElementGuid>df648e40-56c1-4fde-8ec9-005e72805d30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gold Chain'])[3]/preceding::a[1]</value>
      <webElementGuid>13a2e713-787f-4315-9532-b2fd969fae4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='The Gold Chain GCH00690002 Ships Faster']/parent::*</value>
      <webElementGuid>f9e12b39-6b5b-4fc9-ae82-934f33ad2612</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/the-gold-chain-gch00690002-ships-faster.html?bid=MTkyMg==')])[2]</value>
      <webElementGuid>0f7e2920-017f-4371-83f0-d76dc78cf298</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/div[2]/div/div/div/h2/a</value>
      <webElementGuid>f0ee9cf4-cb17-43cf-8574-4b769462b978</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/the-gold-chain-gch00690002-ships-faster.html?bid=MTkyMg==' and (text() = 'The Gold Chain GCH00690002 Ships Faster' or . = 'The Gold Chain GCH00690002 Ships Faster')]</value>
      <webElementGuid>d719597b-d54b-4795-96dc-a4a18415567f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
