<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Are you sure want to delete this item</name>
   <tag></tag>
   <elementGuidId>ae648ed5-cb2a-402e-827f-d807c67ae24b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='popup_message']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#popup_message</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b2cb121a-270e-4f62-8393-d3c0d9579740</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>popup_message</value>
      <webElementGuid>f121a4f9-cbff-4e8f-8a2f-f0d7ff867eaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Are you sure want to delete this item ?</value>
      <webElementGuid>c358ff3d-a61b-4b5b-a516-82411845d7e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;popup_message&quot;)</value>
      <webElementGuid>ffee1e37-677d-4654-956a-a4846b1df0ab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='popup_message']</value>
      <webElementGuid>8ee48c0f-d893-4d6e-a351-46af32658d73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='popup_content']/div</value>
      <webElementGuid>ff6a7db5-93ca-45d3-8ab2-5a4085e6f419</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alert'])[1]/following::div[2]</value>
      <webElementGuid>2a690695-d6ea-4881-a5d3-a6db17f2fa8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'popup_message', '&quot;', ')')])[1]/following::div[6]</value>
      <webElementGuid>079e092a-9c88-401f-9cb0-fd4148483545</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Are you sure want to delete this item ?']/parent::*</value>
      <webElementGuid>7d44aa53-80a5-4d33-9ee1-248f196d7e00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div</value>
      <webElementGuid>fea64a93-259b-4c14-bbad-fccad4c61347</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'popup_message' and (text() = 'Are you sure want to delete this item ?' or . = 'Are you sure want to delete this item ?')]</value>
      <webElementGuid>369c6cfa-18e3-487a-b299-489a48ba8b27</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
