<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Item removed successfully</name>
   <tag></tag>
   <elementGuidId>f7b2526f-9ec0-40af-a9a9-d322134f8565</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='common_message']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#common_message</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>36bf1128-eccc-4a09-901f-d7112d9f0440</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>common_message</value>
      <webElementGuid>e64f3cf9-8956-42c2-8f05-ae38b4018d98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>message_info</value>
      <webElementGuid>e0b0e713-9390-4940-9d3c-1f6c53e5af56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Item removed successfully</value>
      <webElementGuid>24e7e16c-86a7-4ec1-8266-70fc5fa10eab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;common_message&quot;)</value>
      <webElementGuid>56a10216-2d55-4efa-8b26-37cb66a736a7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='common_message']</value>
      <webElementGuid>7d94ee69-761f-4b18-9644-849f6870e206</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-wrapper']/div[2]/div[2]/div[2]/div/div/div[2]</value>
      <webElementGuid>40a3c2d1-8d46-400d-b93f-e7532beb326d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='₹177,795'])[1]/following::div[5]</value>
      <webElementGuid>8bdc6194-ea94-4459-8b87-9f1b618dcb16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total Amount'])[1]/following::div[6]</value>
      <webElementGuid>eded70f2-849d-4dd5-9fb7-1383f97cdd80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product'])[1]/preceding::div[2]</value>
      <webElementGuid>935aefe0-e919-44ae-b59e-139b27df55b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Description'])[1]/preceding::div[2]</value>
      <webElementGuid>9c051e17-3b14-48da-b162-d1624f806787</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Item removed successfully']/parent::*</value>
      <webElementGuid>d797a3cb-dcf3-4bf9-9553-111ffaa1e24d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div[2]</value>
      <webElementGuid>8c349203-e5fd-4b41-9463-7b8759d96b9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'common_message' and (text() = 'Item removed successfully' or . = 'Item removed successfully')]</value>
      <webElementGuid>4ff5f5b0-bdba-4c04-8d9e-f13e64f9897a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
