<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_11</name>
   <tag></tag>
   <elementGuidId>c856692d-369d-48f5-8cbb-277a8b853e63</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='opt_57789_264862']/div/ul/li[6]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>82ac2251-9fb8-4be6-b925-421fa38b43d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>1561182</value>
      <webElementGuid>f3d89645-906f-492a-9c07-fdc8289cf683</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>31db2a0c-dcca-4798-bc9e-42bb603c7cc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>11</value>
      <webElementGuid>ecce5d72-080a-428b-ae9a-1e9a7458d0cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;opt_57789_264862&quot;)/div[@class=&quot;nice-select listbox pull-left form-control custom_option inv_no variantAddtoCart open&quot;]/ul[@class=&quot;list&quot;]/li[@class=&quot;option&quot;]</value>
      <webElementGuid>bef03bf8-5a56-474a-8ee0-98dbef9a7290</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='opt_57789_264862']/div/ul/li[6]</value>
      <webElementGuid>2966e694-05b7-4a30-9332-21941b47110b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Size'])[3]/following::li[5]</value>
      <webElementGuid>1045d0dc-3b65-484b-99e1-23fa016bb2a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Size'])[2]/following::li[6]</value>
      <webElementGuid>c85c469d-cffb-4a1e-a8a1-e5f48a1f4c5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please select size'])[1]/preceding::li[11]</value>
      <webElementGuid>13f57b89-cced-4da3-bf5c-d0301d480830</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Size chart'])[1]/preceding::li[11]</value>
      <webElementGuid>c1bd9b21-9580-4087-ba6b-7206423f5f67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/div/ul/li[6]</value>
      <webElementGuid>051200d4-5edd-4864-ba77-925d36483dae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = '11' or . = '11')]</value>
      <webElementGuid>3df79b00-ca65-49ed-aa67-5579ffbf3d54</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
