<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_12</name>
   <tag></tag>
   <elementGuidId>a78d1138-cb29-4507-93ab-8bfd07f6eaa0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='opt_1070_165243']/div/ul/li[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>367a2aab-4ea6-404c-bb92-467181e1e0d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>1584884</value>
      <webElementGuid>cecf2abf-a766-4787-9478-8cd98741243b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>0c05a1a8-574b-4d06-936a-2755590bd93d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>6269790e-2c71-46f0-88b8-c1fe58a40d36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;opt_1070_165243&quot;)/div[@class=&quot;nice-select listbox pull-left form-control custom_option inv_no variantAddtoCart open&quot;]/ul[@class=&quot;list&quot;]/li[@class=&quot;option&quot;]</value>
      <webElementGuid>a7392074-6588-47ce-8e77-14ad5d8f3c42</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='opt_1070_165243']/div/ul/li[3]</value>
      <webElementGuid>00d131c9-81ca-43df-bb70-fa347f4b1274</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='{11'])[2]/following::li[1]</value>
      <webElementGuid>f81c5344-3bb9-41e8-839b-4393080a6440</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Size'])[3]/following::li[2]</value>
      <webElementGuid>dc901085-b337-405d-a368-da9dfbc306ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please select size'])[1]/preceding::li[12]</value>
      <webElementGuid>ef9be000-8e4e-4d79-bf66-2ce0cad865b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Size chart'])[1]/preceding::li[12]</value>
      <webElementGuid>1faf318b-6548-47ee-9a3f-1ca9cfd82fb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/div/ul/li[3]</value>
      <webElementGuid>0847c0bb-b0ef-40b2-a9dd-2308497fb8c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = '12' or . = '12')]</value>
      <webElementGuid>29be05dc-45f0-480f-9cb1-add962e62171</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
