<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Select Size</name>
   <tag></tag>
   <elementGuidId>88225bf3-3ebb-4d91-bbe3-b91343619a64</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='opt_57789_264862']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.nice-select.listbox.pull-left.form-control.custom_option.inv_no.variantAddtoCart</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>18aa2ac2-4e4e-467f-91ab-c43a61447bcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nice-select listbox pull-left form-control custom_option inv_no variantAddtoCart</value>
      <webElementGuid>7fe4a355-c51c-4830-ab06-43135f8e9d9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>64e85ffd-6cb2-44f2-adba-c699bde37131</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select SizeSelect Size070809101112131415161718192021</value>
      <webElementGuid>0900b0d3-b130-4982-b067-202a9b4ebb02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;opt_57789_264862&quot;)/div[@class=&quot;nice-select listbox pull-left form-control custom_option inv_no variantAddtoCart&quot;]</value>
      <webElementGuid>3ddd1a07-fb10-42e1-bfc7-f7ed43dc4e89</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='opt_57789_264862']/div</value>
      <webElementGuid>0b867342-f3fb-48c0-9988-d2c01424f578</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Size :'])[1]/following::div[1]</value>
      <webElementGuid>95bcd1f4-6c13-4495-989a-487f1caa8d10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(Inclusive of all taxes)'])[2]/following::div[4]</value>
      <webElementGuid>1888ba5c-7038-4829-8a9f-eb22471b3d9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/div</value>
      <webElementGuid>8f83de0f-dd62-4593-9c83-78092ba133c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Select SizeSelect Size070809101112131415161718192021' or . = 'Select SizeSelect Size070809101112131415161718192021')]</value>
      <webElementGuid>53830163-1555-47dc-9a6e-22630c19b8c0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
