<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Select Size</name>
   <tag></tag>
   <elementGuidId>83983594-2ece-402f-bce5-6fd706b2e3d0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='opt_1070_165243']/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.current</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>006e4723-f128-4e22-a6ff-daafd4b4c862</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>current</value>
      <webElementGuid>68714541-a4e3-4996-a3f1-e42077546e8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select Size</value>
      <webElementGuid>3492ad71-8bdf-483c-a184-644cbb771b0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;opt_1070_165243&quot;)/div[@class=&quot;nice-select listbox pull-left form-control custom_option inv_no variantAddtoCart&quot;]/span[@class=&quot;current&quot;]</value>
      <webElementGuid>8fdf5de3-398a-4be1-bc27-bfdef7b8777b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='opt_1070_165243']/div/span</value>
      <webElementGuid>9d9bfc50-9eac-4324-b255-f68d839336b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Size :'])[1]/following::span[1]</value>
      <webElementGuid>65ec121b-d969-4cd1-806e-21dd048e8b17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(Inclusive of all taxes)'])[2]/following::span[1]</value>
      <webElementGuid>5912c456-1176-4d43-ad79-387b5e55e7d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Size'])[3]/preceding::span[1]</value>
      <webElementGuid>0db36690-7731-45c0-b2f7-e0f036894181</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='{11'])[2]/preceding::span[1]</value>
      <webElementGuid>b68a9046-7833-4e0e-ad5a-a1d8adde26f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/div/span</value>
      <webElementGuid>c3c27372-b4ff-477c-b0b1-e3170dddbdfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Select Size' or . = 'Select Size')]</value>
      <webElementGuid>42d89111-fc5a-4d32-b319-bc3010c6a95d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
