<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TextShoppingBag</name>
   <tag></tag>
   <elementGuidId>b3c8d72f-d321-4dfe-b358-938e99a40d17</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content-wrapper']/div[2]/div[2]/div/h3</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h3.text-uppercase.cart-ttl</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>dee18f5a-2f61-4051-8947-40c5507f690d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-uppercase cart-ttl</value>
      <webElementGuid>dcf36cc1-5317-47a1-80e4-78bbc287830b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Shopping Bag 1 item(s)</value>
      <webElementGuid>61f0adb0-0981-41a3-9a72-ef85158835d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content-wrapper&quot;)/div[@class=&quot;clearfix&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;carttop&quot;]/h3[@class=&quot;text-uppercase cart-ttl&quot;]</value>
      <webElementGuid>eabccb21-c9f9-4f52-ba15-4e715b2ee09d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-wrapper']/div[2]/div[2]/div/h3</value>
      <webElementGuid>edde825c-3caa-40cc-9ebf-a31660222074</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shopping Cart'])[1]/following::h3[1]</value>
      <webElementGuid>29468ccc-9586-464d-ad9e-9cd736c3da26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/following::h3[1]</value>
      <webElementGuid>18ae1369-789e-4b91-af85-1223e60951c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total Amount'])[1]/preceding::h3[1]</value>
      <webElementGuid>4e76bf45-fa04-49de-a917-b03dd279e04f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='₹455,581'])[1]/preceding::h3[1]</value>
      <webElementGuid>220e43ca-0c33-4b43-ba2f-5f29089c47ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Shopping Bag']/parent::*</value>
      <webElementGuid>fdd198c3-6f25-41b5-aef0-8e90815dc50b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3</value>
      <webElementGuid>1df7dc44-aae3-4b01-a0c6-52f520b4a95e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h3[(text() = 'Shopping Bag 1 item(s)' or . = 'Shopping Bag 1 item(s)')]</value>
      <webElementGuid>a7fcfa68-f135-4971-b616-8dbea1cc4e0e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
