<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Invalid UsernamePassword</name>
   <tag></tag>
   <elementGuidId>12b19c49-faca-42a8-9a61-3222fa7e15a5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#common_login_message</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='common_login_message']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>376b896d-b735-4dda-80f2-29348163c52e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>common_login_message</value>
      <webElementGuid>efa23d1a-da55-4730-bc40-33c76569621b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>message_error</value>
      <webElementGuid>25c6f648-1847-420e-b263-2f973aed3257</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Invalid Username/Password</value>
      <webElementGuid>624b9011-1dc7-4685-9c14-97ee06c84616</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;common_login_message&quot;)</value>
      <webElementGuid>049f7a41-fbae-4373-8cd1-b0ec6b4b6880</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/LoginWindow/iframe_Loading_loginPopup</value>
      <webElementGuid>6a2b8087-3a06-42b9-854b-628c377dc152</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='common_login_message']</value>
      <webElementGuid>0d255344-79ee-4a5e-bed9-17c3b1325f4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign Up'])[1]/following::div[4]</value>
      <webElementGuid>5967177b-4a87-4553-8cd1-8194163b46be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[1]/following::div[4]</value>
      <webElementGuid>086201ee-8d2c-4a92-a3fb-f9a9825633d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[2]/preceding::div[1]</value>
      <webElementGuid>e24f2d72-1da3-4939-ab14-a6e9c41c6315</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter Email Address~*Enter valid email address ~*Scripts are not allowed'])[1]/preceding::div[1]</value>
      <webElementGuid>4ecf19cd-1033-468d-9294-f5367d0f43b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Invalid Username/Password']/parent::*</value>
      <webElementGuid>62b37cea-fc51-4dbf-9238-a80e0233d0eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]</value>
      <webElementGuid>3585a5ab-f1bc-4dcd-a342-c8dc8979171d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'common_login_message' and (text() = 'Invalid Username/Password' or . = 'Invalid Username/Password')]</value>
      <webElementGuid>b7ee49f3-4519-4d1c-887a-9e8b22508c0c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
