<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>RingsLink</name>
   <tag></tag>
   <elementGuidId>416c65dd-15cd-4f5e-8518-3a945f661267</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main']/header/div[2]/div/div[2]/div/ul/li[3]/ul/li/ul/li/a</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//ul[@class='main-navigation']//li[@class='current ']//a[text()='Best Sellers']/./following-sibling::ul//ul//a[text()='Rings']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>69ec723a-e5f4-4229-a056-6cff49e07edd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/jewellery/best-seller/rings.html</value>
      <webElementGuid>ef410cd8-3fae-4afb-87ba-ad54471e8baf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Rings</value>
      <webElementGuid>3466d585-3d29-4850-b55c-184d196b4199</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>editedx</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/header[@class=&quot;affix-top&quot;]/div[@class=&quot;header-bottom&quot;]/div[@class=&quot;container clearfix pos-rel&quot;]/div[@class=&quot;clearfix&quot;]/div[@class=&quot;site_main_menu c-buttons&quot;]/ul[@class=&quot;main-navigation&quot;]/li[@class=&quot;current&quot;]/ul[1]/li[1]/ul[1]/li[@class=&quot;no-child&quot;]/a[1]</value>
      <webElementGuid>2b088560-a691-48b0-9828-373c60de1333</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//ul[@class='main-navigation']//li[@class='current ']//a[text()='Best Sellers']/./following-sibling::ul//ul//a[text()='Rings']</value>
      <webElementGuid>39a7e98e-3a6c-4e0e-b0d4-077af6d0e3cf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/header/div[2]/div/div[2]/div/ul/li[3]/ul/li/ul/li/a</value>
      <webElementGuid>d31edf45-45cb-4ac5-b493-5cf45e16fd46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Rings')])[3]</value>
      <webElementGuid>16c08b6a-9390-40b7-8c40-8ed52e3dccca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='By Category'])[1]/following::a[1]</value>
      <webElementGuid>8b95986d-6ed5-4382-9f51-3c804ade84ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Best Sellers'])[1]/following::a[1]</value>
      <webElementGuid>c014e5cd-b9fc-4498-b56f-a65eb8132a22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Earrings'])[2]/preceding::a[1]</value>
      <webElementGuid>117f932a-8f77-413e-aad6-29c8cde7fff3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pendants'])[1]/preceding::a[2]</value>
      <webElementGuid>189622f7-d924-4093-ae3f-9cfc54eacc85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/jewellery/best-seller/rings.html')])[2]</value>
      <webElementGuid>1a7c6e1a-746d-41dc-b91f-f5ff5a2f1020</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/ul/li/ul/li/a</value>
      <webElementGuid>887e4744-70bc-48b5-936a-7943e7b0d91e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/jewellery/best-seller/rings.html' and (text() = 'Rings' or . = 'Rings')]</value>
      <webElementGuid>3ad86446-8c4a-4b6c-b6e3-f6c19a76abe0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
