<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_ADD TO CART</name>
   <tag></tag>
   <elementGuidId>84480e8b-d579-47fc-8b59-a6ae57290438</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='addToCartItem']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#addToCartItem</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b5c97296-6d32-49f9-93ed-99ebe930fa27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>Javascript:void(0);</value>
      <webElementGuid>ab04765d-416b-44dc-bb21-0c16cc469580</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>addToCart  btn btn-secondary btn-block  btn-lg buynow xButton gg</value>
      <webElementGuid>4572f365-7312-48b5-9707-28a12c20ea1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>addToCartItem</value>
      <webElementGuid>26f742fd-dc80-400a-b8bf-c460e559ee82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>2644-2644-1-18645</value>
      <webElementGuid>b6ef41ca-e9e9-484a-8190-df9a42d6fd62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ADD TO CART</value>
      <webElementGuid>70095ebf-4400-4882-ad8e-d0d8e3c3287a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;addToCartItem&quot;)</value>
      <webElementGuid>696a242c-832b-404f-a339-ce2b6c030dc0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='addToCartItem']</value>
      <webElementGuid>b3f64b42-e95f-4d73-a28c-a755bf37561f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='buynow-btn']/div/div/div/a</value>
      <webElementGuid>28cb199e-f075-42f7-9545-a6fbe12d13f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'ADD TO CART')]</value>
      <webElementGuid>27b79016-ecc9-40cf-bdfc-33bd6b52d141</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter comment'])[1]/following::a[1]</value>
      <webElementGuid>dfb889ff-a45a-4aad-8715-018c633b0799</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WHAT WOULD YOU LIKE TO CHANGE IN THIS DESIGN?'])[1]/following::a[1]</value>
      <webElementGuid>92c2eb0b-9193-485d-9497-058f5d7fa3e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Buy Now'])[1]/preceding::a[2]</value>
      <webElementGuid>f280ee9b-903b-469f-890c-7c3facb11fd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name'])[2]/preceding::a[5]</value>
      <webElementGuid>14c99f48-e821-4540-9e9f-89515f26d27e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ADD TO CART']/parent::*</value>
      <webElementGuid>784c8d75-1049-4e57-b35a-fb087497411c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'Javascript:void(0);')])[9]</value>
      <webElementGuid>16c79b4b-0bad-4df4-aad0-606ba4842a7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/div/a</value>
      <webElementGuid>3945c9ab-67ec-47ee-8bb3-3ddc289526e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'Javascript:void(0);' and @id = 'addToCartItem' and (text() = 'ADD TO CART' or . = 'ADD TO CART')]</value>
      <webElementGuid>52bb395f-2343-446f-af85-1417a5633938</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
