<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_ADD TO CART (1)</name>
   <tag></tag>
   <elementGuidId>17905ed6-55fc-4b00-b8f0-b80ccb15f88a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='addToCartItem']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#addToCartItem</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e621db72-6ae3-42d2-b9b8-3d3d759702d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>Javascript:void(0);</value>
      <webElementGuid>5e6b5882-030f-427f-a4b8-b2032ca372fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>addToCart  btn btn-secondary btn-block  btn-lg buynow xButton gg</value>
      <webElementGuid>10587251-0fb3-4f76-ac4d-69210d56544f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>addToCartItem</value>
      <webElementGuid>75588bf9-d28b-49e9-a425-5d02c3c7469b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>2644-2644-1-18645</value>
      <webElementGuid>d937e892-75a3-405b-b6da-a6e00a21f7bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ADD TO CART</value>
      <webElementGuid>a83b8664-dfe2-4070-ac6f-3684656d3eb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;addToCartItem&quot;)</value>
      <webElementGuid>3e7ab9fe-5740-4c14-bee3-4fa954e1fa03</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='addToCartItem']</value>
      <webElementGuid>426b913f-b701-4eb1-8bac-5cf89dadd2f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='buynow-btn']/div/div/div/a</value>
      <webElementGuid>ab73c3be-66ba-40fb-826b-2267f3f881c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'ADD TO CART')]</value>
      <webElementGuid>2eb6e912-5b21-458c-8502-bc3b36798f9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter comment'])[1]/following::a[1]</value>
      <webElementGuid>96c1fd93-2204-4495-8481-9d06bc78578c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WHAT WOULD YOU LIKE TO CHANGE IN THIS DESIGN?'])[1]/following::a[1]</value>
      <webElementGuid>173a25e3-237d-4f83-96cb-a764cbc86a3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Buy Now'])[1]/preceding::a[2]</value>
      <webElementGuid>9c9dc3cf-0b06-4bd2-b3be-d4983e0328a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name'])[2]/preceding::a[5]</value>
      <webElementGuid>49966ac0-40e4-4be9-aa84-178307f583b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ADD TO CART']/parent::*</value>
      <webElementGuid>8ebbe5d3-667d-4ed0-94ff-d28e88f016c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'Javascript:void(0);')])[9]</value>
      <webElementGuid>95d16286-37df-45f9-bcc5-4b292ca83e6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/div/a</value>
      <webElementGuid>b37d10e4-807d-43af-aa9b-e3c8af752491</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'Javascript:void(0);' and @id = 'addToCartItem' and (text() = 'ADD TO CART' or . = 'ADD TO CART')]</value>
      <webElementGuid>04acf33b-1c08-4501-899d-4156f3bee367</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
