<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_Digital Gold</name>
   <tag></tag>
   <elementGuidId>53c237e5-7fac-4f9a-a232-87a9e3e8cf8f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='printableArea']/div[5]/div/div/h1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>404840fe-ade4-4a80-8115-46f3044fe29b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Digital Gold</value>
      <webElementGuid>92ecb071-c487-4b4b-a5eb-5ccf7a87688e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;printableArea&quot;)/div[@class=&quot;cms_area default-style&quot;]/div[@class=&quot;top-content light-bg&quot;]/div[@class=&quot;dg&quot;]/h1[1]</value>
      <webElementGuid>7131b183-4a81-45df-89ce-899d27fd02ad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='printableArea']/div[5]/div/div/h1</value>
      <webElementGuid>65d4baa8-5f0c-42de-bbdd-4587f817f8e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/following::h1[1]</value>
      <webElementGuid>69908fa4-c71e-4c56-8700-377e32122996</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Buy Now'])[1]/preceding::h1[1]</value>
      <webElementGuid>6b575552-1ab5-47e8-9c40-29d200c6f995</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='What is Digital Gold'])[1]/preceding::h1[1]</value>
      <webElementGuid>91cc0f58-71bc-42d6-9dfa-de517958ef63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>ec54028e-5715-44fb-96b8-e978190bbcc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'Digital Gold' or . = 'Digital Gold')]</value>
      <webElementGuid>a2bf915b-6755-43cd-b921-87e94b2a1521</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
