<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_Collections</name>
   <tag></tag>
   <elementGuidId>3e3d2a88-e3ec-4014-9746-fb9c87f790a3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content-wrapper']/div/div[5]/h1</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>61cb8bdf-bbe3-4400-beb9-3a810c46d2d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>caption1 h4style  rmv-padding pull-left text-uppercase </value>
      <webElementGuid>2ce78318-1137-456e-ae20-e7f726248a35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
Collections
</value>
      <webElementGuid>7e4ae0c8-26d0-41fa-a1e4-1bdc016b75fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content-wrapper&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;clearfix border-bottom head-wrap&quot;]/h1[@class=&quot;caption1 h4style  rmv-padding pull-left text-uppercase&quot;]</value>
      <webElementGuid>51317aac-42d3-4d72-8817-aa8b10f1c8b3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-wrapper']/div/div[5]/h1</value>
      <webElementGuid>d71e8d64-7236-4319-9e32-66cdbc84b642</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jewellery'])[1]/following::h1[1]</value>
      <webElementGuid>fbc0d384-c320-4b42-8ccb-6f1b233cb8b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/following::h1[1]</value>
      <webElementGuid>0649c9a2-9287-4de2-8ece-0d4378f44050</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FILTER BY'])[1]/preceding::h1[1]</value>
      <webElementGuid>eaf1e074-34d4-45a3-a1de-0cd79eaf7d20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>3ba866c0-20a7-47bc-ae82-d838f8373e64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = '
Collections
' or . = '
Collections
')]</value>
      <webElementGuid>cefab3db-a108-4c35-a349-88c09a0e5a97</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
