<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>a2c61e39-1a63-4f1d-8aac-34ba50ef08d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.img-responsive.hidden-xs.hidden-sm > img[alt=&quot;PCJeweller&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='logo']/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>8b3eeb94-f984-4a54-a194-7877337f5dac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://cf-cdn.pcjeweller.com/public/uploads/settings/pcj-logo__592261435__1103462098.png</value>
      <webElementGuid>6e858ee3-a563-41fe-ad36-4a1e7acf0d18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>border</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>8bcf9969-a567-4df5-9424-5c33469a78ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>PCJeweller</value>
      <webElementGuid>d9f982e3-d457-46d8-871d-2d8f56c64d83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>80</value>
      <webElementGuid>ddf93e93-e9fb-4acf-bac2-284b9885a96b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;logo&quot;)/a[@class=&quot;img-responsive hidden-xs hidden-sm&quot;]/img[1]</value>
      <webElementGuid>e417b584-d8b7-400c-bb7c-65dd866b55c7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='logo']/a/img</value>
      <webElementGuid>789e7bdf-85d0-4265-a8eb-a5de6edc484d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='PCJeweller'])[2]</value>
      <webElementGuid>e3f33fcd-59fa-4b41-b848-0e966f54507f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/a/img</value>
      <webElementGuid>4dcb5158-91a3-485d-9dd1-136c316d3ed0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://cf-cdn.pcjeweller.com/public/uploads/settings/pcj-logo__592261435__1103462098.png' and @alt = 'PCJeweller']</value>
      <webElementGuid>7be4b029-a5d6-46ce-9674-95effefeed26</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
