<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>brokenPage</name>
   <tag></tag>
   <elementGuidId>f3da0045-74c2-426a-9ac8-2197f96ec439</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//body[@id='t']//div[@id='main-frame-error']//div[@id='main-message']//span[contains(text(),'reached')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//body[@id='t']//div[@id='main-frame-error']//div[@id='main-message']//span[contains(text(),'reached')]</value>
      <webElementGuid>5c580381-24ba-4b9d-b3f5-548db8a424dc</webElementGuid>
   </webElementProperties>
</WebElementEntity>
