<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>BestSellerLink</name>
   <tag></tag>
   <elementGuidId>2242ca51-52ce-4ae9-94be-5635c3783b5a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main']/header/div[2]/div/div[2]/div/ul/li[3]/a</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@href = '/jewellery/best-sellers.html' and (text() = 'Best Sellers' or . = 'Best Sellers')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>bc786d35-6689-46ad-abb9-6820d627e02e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/jewellery/best-sellers.html</value>
      <webElementGuid>c5017157-4e6c-4ddb-aeb2-1561a90dbabe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Best Sellers</value>
      <webElementGuid>5abc9bb3-333c-4f18-ae75-043d8a22c150</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/header[@class=&quot;affix-top&quot;]/div[@class=&quot;header-bottom&quot;]/div[@class=&quot;container clearfix pos-rel&quot;]/div[@class=&quot;clearfix&quot;]/div[@class=&quot;site_main_menu c-buttons&quot;]/ul[@class=&quot;main-navigation&quot;]/li[3]/a[1]</value>
      <webElementGuid>01fb1122-0e0e-40da-8872-037104851154</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/header/div[2]/div/div[2]/div/ul/li[3]/a</value>
      <webElementGuid>4850dcc2-43df-4dfb-8dfe-ddb1dbb26282</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Best Sellers')]</value>
      <webElementGuid>9ccc9020-a65d-41e8-955d-250fe8636e38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View All Earrings'])[1]/following::a[1]</value>
      <webElementGuid>1b31233a-76c8-4820-ac43-64f2883f4990</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gemstone'])[2]/following::a[2]</value>
      <webElementGuid>dbfe0c66-8dba-437e-8508-cedc894ffff5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='By Category'])[1]/preceding::a[1]</value>
      <webElementGuid>d76db271-4eda-48ae-8034-e3798f0cf54c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rings'])[2]/preceding::a[1]</value>
      <webElementGuid>34e6e5a2-2dc2-4f4c-827d-87e3ecd1351e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Best Sellers']/parent::*</value>
      <webElementGuid>de9b4088-22ae-4a9d-a15b-2cb650c0999e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/jewellery/best-sellers.html')]</value>
      <webElementGuid>14455706-257e-4dcb-96fc-4c0ebc681c59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/a</value>
      <webElementGuid>bfd4ea30-564f-4337-a7c7-fc3f722ed77d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/jewellery/best-sellers.html' and (text() = 'Best Sellers' or . = 'Best Sellers')]</value>
      <webElementGuid>7c8de237-5004-4c7f-9802-35fef0cdf6d0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
