<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>chatButton</name>
   <tag></tag>
   <elementGuidId>86965158-ca99-483c-92f5-a41ce1ec32de</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;chat&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='chat']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>92a59f2a-80e8-40db-8c5e-8acbd5707c40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>chat</value>
      <webElementGuid>5df371f3-f64f-4197-b986-967c7c61b6e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chat</value>
      <webElementGuid>b3e56db5-b442-4abc-9186-70a40318f175</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>chat</value>
      <webElementGuid>e35f10d0-e8bb-4ccf-88c0-06e89b1f1736</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>if (!window.__cfRLUnblockHandlers) return false; onClick()</value>
      <webElementGuid>3145880a-2a8f-4d8b-8671-23d56ebcd515</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>506d8431-6414-4d7d-bc8e-f2e9acf31668</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/header[@class=&quot;affix-top&quot;]/div[@class=&quot;header-top&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;hidden-xs hidden-sm&quot;]/form[@class=&quot;chatbutton&quot;]/input[@class=&quot;chat&quot;]</value>
      <webElementGuid>26892d54-2f3e-4d0b-8e14-58d8ba500321</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='chat']</value>
      <webElementGuid>21b8d46d-7634-4ced-80b4-68ee4bbd9b52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/header/div/div/div/form/input</value>
      <webElementGuid>1d5199e8-d659-424d-93f6-f15ddd9c92d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/input</value>
      <webElementGuid>cfd5c209-1966-4369-86ac-1edff3019b34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@alt = 'chat' and @name = 'chat' and @type = 'button']</value>
      <webElementGuid>4c635288-6367-43f1-bffa-0cb1249f485a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
