<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>chatDialogueCloseButton</name>
   <tag></tag>
   <elementGuidId>4b6557b6-702a-466c-a705-231740efe16b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.close-icon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div[2]/div/div/div[2]/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>053c9f10-18b3-42df-bd61-addffa91e9a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>close-icon</value>
      <webElementGuid>c2b463f4-bfbd-4ee3-960d-9afb9e7ac2e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>close-widget</value>
      <webElementGuid>7ec571b6-250d-4412-baa4-e4254b82f505</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Close</value>
      <webElementGuid>e73bfaef-3624-49e9-ab9a-b889c7987009</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;chat-widget widget-animation-enter-done&quot;]/div[@class=&quot;sc-htpNat DZhvI&quot;]/div[@class=&quot;header&quot;]/div[@class=&quot;action-button&quot;]/div[@class=&quot;close-icon&quot;]</value>
      <webElementGuid>b4c81a39-9027-4f3b-8754-fe00e550abf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Gold  Diamond  Online Jewellery Shoppi_0b87d1/iframe_concat(id(, , selekt-chat-widget, , _6c8b0e</value>
      <webElementGuid>02764d44-ea87-412f-97d2-56fd26babf74</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[2]/div/div/div[2]/div[2]</value>
      <webElementGuid>34d58c83-123e-43b1-934e-9961dffed02e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PC Jeweller'])[1]/following::div[4]</value>
      <webElementGuid>33f79cf1-11e6-4dea-84cc-fc938622faf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PC Jeweller'])[2]/preceding::div[1]</value>
      <webElementGuid>842bdc03-b3e5-4a55-b3bc-18a96e43d732</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Check Delivery at my Pincode'])[1]/preceding::div[26]</value>
      <webElementGuid>05e31e71-4c32-4da8-ab79-55ab25786015</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div[2]</value>
      <webElementGuid>c8f1e81e-c02b-4439-a364-5354753bd15d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@title = 'Close']</value>
      <webElementGuid>63e7803c-941f-45df-87b6-48ac652a5351</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
