<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>chatDialogueBox</name>
   <tag></tag>
   <elementGuidId>8d297d7f-e419-4087-977c-39266bb619b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#app</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c24c5790-c59b-4e21-8e13-46620df5f288</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>app</value>
      <webElementGuid>896ea834-4707-4254-91bb-37adb1fb5570</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PC Jeweller0PC JewellerHello 'There'! 👋 Welcome to PC Jeweller. I am your Virtual AssistantWhat do you need help with?Check Delivery at my PincodeRing &amp; Bangle Size GuideReturns &amp; Exchanges PolicyCancellation PolicyTrack my OrderGold Rate TodayHelp me ShopAny other QueryRequest a Call BackPowered by ChatGen</value>
      <webElementGuid>47768d8b-0e09-4cf8-bdd6-3a5114dfd2fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)</value>
      <webElementGuid>f31c601c-f4a3-4ea3-9b1d-1045e5ea3b3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Gold  Diamond  Online Jewellery Shoppi_0b87d1/iframe_concat(id(, , selekt-chat-widget, , _6c8b0e</value>
      <webElementGuid>e2606dcb-b4da-4de8-9db8-68377120aaf5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='app']</value>
      <webElementGuid>4468a18a-6718-48bc-aa08-7e277b0b263d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div</value>
      <webElementGuid>2f6dc27d-2d9a-4cf7-934c-a500bd489dd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'app' and (text() = concat(&quot;PC Jeweller0PC JewellerHello &quot; , &quot;'&quot; , &quot;There&quot; , &quot;'&quot; , &quot;! 👋 Welcome to PC Jeweller. I am your Virtual AssistantWhat do you need help with?Check Delivery at my PincodeRing &amp; Bangle Size GuideReturns &amp; Exchanges PolicyCancellation PolicyTrack my OrderGold Rate TodayHelp me ShopAny other QueryRequest a Call BackPowered by ChatGen&quot;) or . = concat(&quot;PC Jeweller0PC JewellerHello &quot; , &quot;'&quot; , &quot;There&quot; , &quot;'&quot; , &quot;! 👋 Welcome to PC Jeweller. I am your Virtual AssistantWhat do you need help with?Check Delivery at my PincodeRing &amp; Bangle Size GuideReturns &amp; Exchanges PolicyCancellation PolicyTrack my OrderGold Rate TodayHelp me ShopAny other QueryRequest a Call BackPowered by ChatGen&quot;))]</value>
      <webElementGuid>ecbad29b-87e5-432a-b3ef-d88bcc0e3679</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
