<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Footer_Overview</name>
   <tag></tag>
   <elementGuidId>f9059352-0180-4391-bc93-3bd7de8cdd5f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='footer']/div/div/div/div/div/div[3]/div/ul/li/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.container.ftr-menu > ul > li > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c49e75f1-8d8a-41ac-816b-1a3797096ca4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Overview</value>
      <webElementGuid>d0d5ddb2-d50d-490b-8553-7d161c659bb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;footer&quot;)/div[@class=&quot;clearfix&quot;]/div[@class=&quot;footerBottom&quot;]/div[@class=&quot;clearfix&quot;]/div[@class=&quot;footermenublock&quot;]/div[@class=&quot;clearfix&quot;]/div[@class=&quot;footermenu hidden-xs hidden-sm&quot;]/div[@class=&quot;container ftr-menu&quot;]/ul[1]/li[1]/span[1]</value>
      <webElementGuid>3d1b3ff9-10ba-4867-8b3e-7ce902360fe9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='footer']/div/div/div/div/div/div[3]/div/ul/li/span</value>
      <webElementGuid>a47ab2e1-a6fb-4bcc-8c6c-4b6468ae1afc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PCJ Store Locator'])[1]/following::span[1]</value>
      <webElementGuid>1835aa00-48ff-4c10-9caa-db8c650fc294</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SHOP WITHOUT WORRY'])[1]/following::span[1]</value>
      <webElementGuid>f5c06193-c8d3-4d86-bbd4-05b537c8ff09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Collections'])[2]/preceding::span[1]</value>
      <webElementGuid>ac63d0fb-db4e-43ce-9a0a-1b840d7ac2a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='About Us'])[1]/preceding::span[1]</value>
      <webElementGuid>aa44a231-450f-4dd9-879d-f3b435e1b501</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Overview']/parent::*</value>
      <webElementGuid>e477711d-ffdf-4e5f-8533-21f29d53af79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ul/li/span</value>
      <webElementGuid>2d123075-5b78-4747-95cf-b6e0de213f0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' Overview' or . = ' Overview')]</value>
      <webElementGuid>d12080bf-c1cd-485e-b575-498245ebe6b1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
