<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>form_Loading_chatbutton</name>
   <tag></tag>
   <elementGuidId>8f4c1a68-8aac-45b1-8578-5efefa7d6dd8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>form.chatbutton</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main']/header/div/div/div/form</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>form</value>
      <webElementGuid>f8732ec8-198c-435d-bd39-1ce4cc64ea88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chatbutton</value>
      <webElementGuid>9b5af488-f36b-4a6e-b9cd-99dd16189908</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/header[@class=&quot;affix-top&quot;]/div[@class=&quot;header-top&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;hidden-xs hidden-sm&quot;]/form[@class=&quot;chatbutton&quot;]</value>
      <webElementGuid>a1759b5a-9975-40c9-8c05-74ad9c0fa34a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/header/div/div/div/form</value>
      <webElementGuid>25f9646a-fe80-4318-82cc-b5902a6e6be7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Corporate Gifting'])[1]/preceding::form[1]</value>
      <webElementGuid>8774832e-2064-4f96-9f7a-c65e26a1ac6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form</value>
      <webElementGuid>16b83e25-d2b8-4ac0-92d2-087a9b28c7e8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
