<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_concat(id(, , selekt-chat-widget, , _6c8b0e</name>
   <tag></tag>
   <elementGuidId>f6032b0b-50b4-4301-b405-7f8692c22438</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#selekt-chat-widget</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='selekt-chat-widget']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>46fbf174-cbc8-4924-a8d3-cb12d8c598f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>selekt-chat-widget</value>
      <webElementGuid>e7f88fb5-a12e-4f4a-9106-1296239cbca0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://techtonikapp.blob.core.windows.net/storage-migration/widget-app/v1.58/index.html</value>
      <webElementGuid>46bf4d1a-d873-4fb0-a8e3-3892e3236522</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;selekt-chat-widget&quot;)</value>
      <webElementGuid>f83ca23e-a111-4e49-9ac7-48ed56c277a3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='selekt-chat-widget']</value>
      <webElementGuid>197692ad-3127-4aea-8374-5fe1e814bc88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//body/iframe</value>
      <webElementGuid>349d94d6-744e-4a78-a637-f1ead37e4c3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'selekt-chat-widget' and @src = 'https://techtonikapp.blob.core.windows.net/storage-migration/widget-app/v1.58/index.html']</value>
      <webElementGuid>7055456e-8264-4182-9dc4-892473ab9d1a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
