<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_PC Jeweller_overlaping-img</name>
   <tag></tag>
   <elementGuidId>0107071a-b273-4aad-acae-b8508b18de92</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.overlaping-img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div[2]/div/div/div/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>34e91034-2d5a-439e-ac87-e7a8b448d2b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>profile-pic0</value>
      <webElementGuid>414c2d39-4571-4a3c-8732-ff0d06e03b39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>overlaping-img</value>
      <webElementGuid>9d8fb563-4fa6-4ef8-b422-cb6573de2b14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>35</value>
      <webElementGuid>36a8e6be-1957-49e6-8da3-5724637b5708</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>35</value>
      <webElementGuid>89b94118-3f5d-49d1-b84e-b11d2121c841</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://app.chatgen.ai/assets/bot-images/5e8c6398d3cbd95ad13702511586424003288.blob</value>
      <webElementGuid>fc2744e5-4383-4aa3-bbd0-9eb8953deb7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;chat-widget widget-animation-enter-done&quot;]/div[@class=&quot;sc-htpNat DZhvI&quot;]/div[@class=&quot;header&quot;]/div[@class=&quot;header-main&quot;]/div[@class=&quot;agent-icons&quot;]/div[@class=&quot;agent-info&quot;]/img[@class=&quot;overlaping-img&quot;]</value>
      <webElementGuid>29aeed2e-633e-4eb2-8b4f-57b9218debf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Gold  Diamond  Online Jewellery Shoppi_0b87d1/iframe_concat(id(, , selekt-chat-widget, , _6c8b0e</value>
      <webElementGuid>37002ef5-56b1-4f87-a305-cc970b9f635d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[2]/div/div/div/div/div/img</value>
      <webElementGuid>c5876d65-9f29-42cb-bd7a-c276d0c025b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://app.chatgen.ai/assets/bot-images/5e8c6398d3cbd95ad13702511586424003288.blob')]</value>
      <webElementGuid>5fd1783e-4d83-410c-86f2-1c576cfb4cc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>eea9924b-b1ac-4681-90c1-a9c077987e3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://app.chatgen.ai/assets/bot-images/5e8c6398d3cbd95ad13702511586424003288.blob']</value>
      <webElementGuid>23f9d564-c1ac-4782-bb02-db37189c9a94</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
