<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Required_submit</name>
   <tag></tag>
   <elementGuidId>dc60bbe5-7dc2-4638-8dfa-0d06d3c4aaef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.clearfix.bttn-bx > #submit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='submit'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>aedd87c7-849d-4627-9eb6-c5c92ea087ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>a47e07b3-e2c1-44f5-af4b-2a8b1deae87e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>15a55c58-85bf-4179-a2ca-326d4f9909bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>1e23b1aa-f3b0-4bc3-bd72-af24c22b0ff3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-block btn btn-primary btn-block submit-signup</value>
      <webElementGuid>91044f56-7c05-4e0e-b903-4830ac32ca37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>form</name>
      <type>Main</type>
      <value>formUserSignup</value>
      <webElementGuid>7ee3c296-3332-4fe3-9ea3-b91822a0426a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Sign up now</value>
      <webElementGuid>8860ae06-9247-4fd9-bc06-752144753b7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formUserSignup&quot;)/div[@class=&quot;signup-form popup-action&quot;]/fieldset[1]/ul[1]/li[@class=&quot;clearfix bttn-bx&quot;]/input[@id=&quot;submit&quot;]</value>
      <webElementGuid>1d932907-47a8-4dca-a277-15bce6baae2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/LoginWindow/loginWinowPopup</value>
      <webElementGuid>88fd2c3c-0ed3-47a4-86cb-9e7585335952</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='submit'])[2]</value>
      <webElementGuid>85b17b24-c2da-4d66-85b5-c0cf9e567bab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formUserSignup']/div/fieldset/ul/li[7]/input</value>
      <webElementGuid>65ccce01-eeab-424e-aa7f-2b0ab1c2c8ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[7]/input</value>
      <webElementGuid>4fdbf187-748e-494e-9d6c-4e9ca922dae9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'submit' and @id = 'submit' and @form = 'formUserSignup']</value>
      <webElementGuid>7e283092-e4b8-47c6-aa72-747998d2413c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
