<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Link_Twitter</name>
   <tag></tag>
   <elementGuidId>90d85c43-7d1b-45d2-8fe5-be3c86ab8e06</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content-wrapper']/div[16]/div[9]/div/a[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.twitter</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>660b6df8-ed72-4ddb-8dc7-b2d9f0771686</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://twitter.com/PCJeweller</value>
      <webElementGuid>a6e616e0-4d1a-4a5b-9241-0a57dbda5ea4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>a69cc205-ca95-414f-ba5b-cc586060ed08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>twitter</value>
      <webElementGuid>74bfaf8d-c25b-4d81-bbe2-cbfde3ef45a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content-wrapper&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;widget-box clearfix hidden-xs hidden-sm&quot;]/div[@class=&quot;social-icon text-center&quot;]/a[@class=&quot;twitter&quot;]</value>
      <webElementGuid>8ed0e7eb-773d-443d-b271-7e8150c6bf76</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-wrapper']/div[16]/div[9]/div/a[2]</value>
      <webElementGuid>f3ce8b98-d64d-44e9-9b43-1aa1a7114574</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://twitter.com/PCJeweller']</value>
      <webElementGuid>e1033633-74a4-4e35-b5b4-0a93035540d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/a[2]</value>
      <webElementGuid>8e068e68-301e-4a27-b211-a70216012f7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://twitter.com/PCJeweller']</value>
      <webElementGuid>2df116a2-b787-4880-9109-b36f3a98de21</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
