<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Link_Instagram</name>
   <tag></tag>
   <elementGuidId>c94cb4d2-ce6a-4270-ba6f-3d081844a72b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content-wrapper']/div[16]/div[9]/div/a[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.instagram</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>62163e6e-40fe-4212-a5e6-2027d243aa76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.instagram.com/pc_jeweller/</value>
      <webElementGuid>948f51ce-c681-4ab2-a198-d35937ea2275</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>0821513b-d82c-4bd0-a233-392f7221bec5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>instagram</value>
      <webElementGuid>8a608b02-a8d4-436b-b406-0bac84929db1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content-wrapper&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;widget-box clearfix hidden-xs hidden-sm&quot;]/div[@class=&quot;social-icon text-center&quot;]/a[@class=&quot;instagram&quot;]</value>
      <webElementGuid>fde69d4d-b653-405f-a8a5-0acdf8112b42</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-wrapper']/div[16]/div[9]/div/a[3]</value>
      <webElementGuid>12067b64-6b62-4bdb-bed9-2cc4a29fd2eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.instagram.com/pc_jeweller/')]</value>
      <webElementGuid>3206d007-1210-48ef-a39d-56a62333169d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/a[3]</value>
      <webElementGuid>43647d4a-c05a-4f6d-a2fa-5915290c8433</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.instagram.com/pc_jeweller/']</value>
      <webElementGuid>8b730806-15d3-47d2-b412-d8216499b4ad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
