<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Link_Facebook</name>
   <tag></tag>
   <elementGuidId>4d1e3bc8-c131-4b3a-be19-58438a7867fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content-wrapper']/div[16]/div[9]/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.facebook.active</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a0db8a1d-cbbb-4907-977b-e7bf16754215</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://facebook.com/PCJINDIA</value>
      <webElementGuid>b80aa574-d042-4c7d-a483-c7b5098dcfb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>cebd0cf1-8fb6-4df1-8b99-7b7cf450ba73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>facebook active</value>
      <webElementGuid>3eadeff5-93f4-4f35-92df-f4826627d194</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content-wrapper&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;widget-box clearfix hidden-xs hidden-sm&quot;]/div[@class=&quot;social-icon text-center&quot;]/a[@class=&quot;facebook active&quot;]</value>
      <webElementGuid>4f75a8f0-e8a2-4527-84f0-c1503cc15f5b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-wrapper']/div[16]/div[9]/div/a</value>
      <webElementGuid>193edc44-d1f5-4a88-9c29-acf113863fee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://facebook.com/PCJINDIA']</value>
      <webElementGuid>a26e4a09-106a-4794-98fb-905f3b078408</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/a</value>
      <webElementGuid>cf8c02c8-8f82-4edc-be6a-c4a4d979404e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://facebook.com/PCJINDIA']</value>
      <webElementGuid>b76130ce-ec78-43ea-a984-c55b3a6d1849</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
