<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Link_WelcomeUser</name>
   <tag></tag>
   <elementGuidId>ba430862-2ec4-4475-adf4-49e3f06c4601</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[contains(@class,'user-account')]//span</value>
      <webElementGuid>79b20c7d-2f1a-4cb2-a408-009b0563dd5d</webElementGuid>
   </webElementProperties>
</WebElementEntity>
