<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Link_Pininterest</name>
   <tag></tag>
   <elementGuidId>b730927d-ade8-4514-8ab5-2ffaad6bc1f9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content-wrapper']/div[16]/div[9]/div/a[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.pininterest</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5e3500ff-3019-4d85-b7de-ee4a0c735527</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://in.pinterest.com/pcjeweller/</value>
      <webElementGuid>904a0c62-eb21-4a73-b4ed-4b740e5bb6a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>b159d554-6048-4c5e-b39d-03a542911383</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pininterest</value>
      <webElementGuid>1e371997-d524-461c-8cec-f34c38772ba4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content-wrapper&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;widget-box clearfix hidden-xs hidden-sm&quot;]/div[@class=&quot;social-icon text-center&quot;]/a[@class=&quot;pininterest&quot;]</value>
      <webElementGuid>92bc7593-b6f3-4182-a858-7311aae8e8b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-wrapper']/div[16]/div[9]/div/a[4]</value>
      <webElementGuid>b02a9b10-8ea8-4411-86e3-e7c8ab8e7ac9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://in.pinterest.com/pcjeweller/')]</value>
      <webElementGuid>72f4c18c-f1e2-4331-9ddd-1ec17c4bd3b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/a[4]</value>
      <webElementGuid>f0da7654-a46c-4e7e-878b-b64fdf5bf732</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://in.pinterest.com/pcjeweller/']</value>
      <webElementGuid>677e8cbb-c731-40e4-a615-b5f95fbe2cdf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
