<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PCJ Store Locator_Text</name>
   <tag></tag>
   <elementGuidId>4adb1b8e-a4e0-475f-9c5c-89f14ebcfc01</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h6.rmv-padding.light.text-uppercase</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='footer']/div/div/div/div/div/div[2]/div/div/div/a/figcaption/h6</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'PCJ Store Locator' or . = 'PCJ Store Locator')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h6</value>
      <webElementGuid>198bbf66-6f38-4f19-ae7b-77de0089bd49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rmv-padding light text-uppercase</value>
      <webElementGuid>7ad15e9f-5fc5-424f-8e0e-6398fab5e836</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PCJ Store Locator</value>
      <webElementGuid>8a4e44dd-da1d-4d79-986e-8f4ec0db4cf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class='footermenublock']//div//figcaption/h6</value>
      <webElementGuid>8d1fde27-aa4e-43d5-b01e-ee992a2b2c39</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='footer']/div/div/div/div/div/div[2]/div/div/div/a/figcaption/h6</value>
      <webElementGuid>daabab41-4838-4e0b-8f06-fae2c028868d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SHOP WITHOUT WORRY'])[1]/following::h6[1]</value>
      <webElementGuid>95d12587-6ade-4bd5-b9a2-d30fc690a9a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Follow Us'])[1]/following::h6[2]</value>
      <webElementGuid>c214d6e0-0052-448d-a805-5aff42ab0b4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Overview'])[1]/preceding::h6[1]</value>
      <webElementGuid>12fba7f1-4aa8-4698-99e1-f24121902215</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Collections'])[2]/preceding::h6[1]</value>
      <webElementGuid>5c358661-f10c-41ea-b370-38ed79ad3515</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='PCJ Store Locator']/parent::*</value>
      <webElementGuid>fcf2abc6-0eab-4399-a4e8-10ae7bc115bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//figcaption/h6</value>
      <webElementGuid>a1768a1a-7732-4810-acf2-fa6ff2e06044</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h6[(text() = 'PCJ Store Locator' or . = 'PCJ Store Locator')]</value>
      <webElementGuid>9acc7ecc-eac4-4292-b58d-a0a3c45208be</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
