<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>searchButton</name>
   <tag></tag>
   <elementGuidId>cd5c2ddf-1a86-484b-a955-8e625d3b652e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#serachButton</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='serachButton']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>33437f4b-d840-4937-90b6-9ba0a9db18a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>adc85de5-5e3d-4cb1-917c-1b4b667509a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>SEARCH</value>
      <webElementGuid>9a2031c8-a580-4356-936c-a51c6074cf07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>serachButton</value>
      <webElementGuid>581c5f65-1a06-49c7-844b-82ce427d08b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary serachBtn</value>
      <webElementGuid>9918f0e2-85cb-4acf-906d-a667306e9657</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>serachButton</value>
      <webElementGuid>cd44dfc2-9899-480b-bc73-be9780031acc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;serachButton&quot;)</value>
      <webElementGuid>a9a775c8-27dc-4022-bb93-028eef799fea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='serachButton']</value>
      <webElementGuid>b084b8f0-0840-43e3-bdb3-f9ce2a9169d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/header/div[2]/div/div/div/div[2]/div/div/span[2]/input</value>
      <webElementGuid>563eaf27-286a-496f-8db7-6e8864212f6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/input</value>
      <webElementGuid>a483a98f-f311-4926-b9ff-1a898818874f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @name = 'serachButton' and @id = 'serachButton']</value>
      <webElementGuid>8de3b185-39d3-4282-b16a-bce5daf6bd4f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
